import 'package:get/get.dart';

class MyLocal extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    "ar": {
      //auth filder
      "welcome": "اهلا وسهلا بك",
      "create": "انشاء",
      "create new account": 'إنشاء حساب جديد',
      "signin": 'تسجيل الدخول',
      "write email": "اكتب البريد",
      "email": "البريد الالكتروني",
      "write password": "اكتب كلمة المرور",
      "password": "كلمة المرور",
      "do not you have account?": "ليس لديك حساب؟",
      "write name": "اكتب الاسم",
      "full name": "الاسم كامل",
      "write number": "اكتب الرقم",
      "phone number": "رقم الهاتف",
      "You already have an account?": "لديك حساب بالفعل؟",
      //Home folder
      "ownership proof": "اثبات ملكية",
      "upload proof hint": "ارفع الاثبات",
      "upload proof": "رفع اثبات",
      "id card passport": "(بطاقة شخصية-جواز سفر)",
      "write your description": "اكتب وصفك",
      "distinctive mark description": "وصف علامة مميزة",
      "upload": "رفع",
      "claim received for review": "تم استلام المطالبة للمراجعة",
      "status": "الحالة",
      "date": "التاريخ",
      "location": "الموقع",
      "location will be determined later": "سيتم تحديده لاحقاً",
      "item description": "وصف الغرض",
      "item registered description":
          "هذا الغرض تم تسجيله بتاريخ. يرجى مراجعة التفاصيل المذكورة أعلاه والتواصل في حال كنت صاحب هذا الغرض.",
      "claim": "مطالبة",
      "done": "تم",
      "profile": "ملفي",
      "notifications": "الإشعارات",
      "search": "البحث",
      "home": "الرئيسية",
      "there are not post at the moment": "لا توجد منشورات حالياً",
      // notification folder
      "no notifications currently": "لا توجد إشعارات حالياً",
      // profile folder
      "edit profile": "تعديل الملف الشخصي",
      "update profile": "تحديث الملف الشخصي",
      "change password": "تغيير كلمة المرور",
      "update your account password": "تحديث كلمة المرور لحسابك",
      "usage policy": "سياسة الاستخدام",
      "view terms and conditions": "الاطلاع على الشروط والأحكام",
      "help and support": "المساعدة والدعم",
      "contact support team": "التواصل مع فريق الدعم",
      "about app": "عن التطبيق",
      "version and app information": "معلومات الإصدار والتطبيق",
      "language": "اللغة",
      "change language": "تغيير اللغة",
      "logout": "تسجيل الخروج",
      "delete account": "حذف الحساب",
      //report folder
      "report": "ابلاغ",
      "report lost item": "ابلاغ عن مفقود",
      "report found item": "ابلاغ عن موجود",
      "electronics": "الكترونيات",
      "wallet": "محفظة",
      "keys": "مفاتيح",
      "bag": "شنطة",
      "other": "أخرى",
      "campus yard": "حرم الجامع",
      "hall": "قاعة",
      "prayer room": "المصلى",
      "report received for review": "تم استلام البلاغ للمراجعة",
      "item name": "اسم الغرض",
      "category": "التصنيف",
      "choose from list": "اختر من القاءمة",
      "write color brand": "اكتب اللون/الماركة",
      "color brand": "اللون/الماركة",
      "describe item": "قم بوصف الغرض",
      "write date": "اكتب التاريخ",
      "lost date": "تاريخ الفقد",
      "write time": "اكتب الوقت",
      "lost time": "وقت الفقد",
      "add image": "اضف صورة",
      "send": "ارسال",
      //search folder
      "search filter": "فلترة البحث",
      "choose type": "اختر النوع",
      "lost": "مفقود",
      "found": "موجود",
      "apply filter": "تطبيق الفلتر",
    },

  "en": {
      // auth folder
      "welcome": "Welcome",
      "create": "Create",
      "create new account": "Create new account",
      "signin": "Sign In",
      "write email": "Enter your email",
      "email": "Email",
      "write password": "Enter your password",
      "password": "Password",
      "do not you have account?": "Don't have an account?",
      "write name": "Enter your name",
      "full name": "Full Name",
      "write number": "Enter your number",
      "phone number": "Phone Number",
      "You already have an account?": "Already have an account?",

      // Home folder
      "ownership proof": "Ownership Proof",
      "upload proof hint": "Upload proof hint",
      "upload proof": "Upload Proof",
      "id card passport": "ID Card / Passport",
      "write your description": "Enter your description",
      "distinctive mark description": "Distinctive mark description",
      "upload": "Upload",
      "claim received for review": "Claim received for review",
      "status": "Status",
      "date": "Date",
      "location": "Location",
      "location will be determined later": "Location will be determined later",
      "item description": "Item Description",
      "item registered description": "This item was registered on. Please review the details and contact if you are the owner.",
      "claim": "Claim",
      "done": "Done", // أضفنا هذا المفتاح
      "profile": "Profile",
      "notifications": "Notifications",
      "search": "Search",
      "home": "Home",
      "there are not post at the moment": "There are no posts at the moment", // أضفنا هذا المفتاح

      // notification folder
      "no notifications currently": "No notifications currently",

      // profile folder
      "edit profile": "Edit Profile",
      "update profile": "Update Profile",
      "change password": "Change Password",
      "update your account password": "Update account password",
      "usage policy": "Usage Policy",
      "view terms and conditions": "View Terms and Conditions",
      "help and support": "Help and Support",
      "contact support team": "Contact Support Team",
      "about app": "About App",
      "version and app information": "Version and App Information",
      "language": "Language",
      "change language": "Change Language",
      "logout": "Logout",
      "delete account": "Delete Account",

      // report folder
      "report": "Report",
      "report lost item": "Report Lost Item",
      "report found item": "Report Found Item",
      "electronics": "Electronics",
      "wallet": "Wallet",
      "keys": "Keys",
      "bag": "Bag",
      "other": "Other",
      "campus yard": "Campus Yard",
      "hall": "Hall",
      "prayer room": "Prayer Room",
      "report received for review": "Report received for review",
      "item name": "Item Name",
      "category": "Category",
      "choose from list": "Choose from list",
      "write color brand": "Enter color/brand",
      "color brand": "Color/Brand",
      "describe item": "Describe the item",
      "write date": "Enter date",
      "lost date": "Lost Date",
      "write time": "Enter time",
      "lost time": "Lost Time",
      "add image": "Add Image",
      "send": "Send",

      // search folder
      "search filter": "Search Filter",
      "choose type": "Choose Type",
      "lost": "Lost",
      "found": "Found",
      "apply filter": "Apply Filter",
    },
  };
}
